### PR TITLE
Include focussed subclasses even if they are in different module

### PR DESCRIPTION
**Pull request by vbraun**
I don't understand the check that the `if inspect.getmodule(thing) is self.current_module` check, the documentation says that focus on any parent class focusses the subclass. Not only if they are defined in the same module. 

In terms of the testsuite, I do want to run `test_non_focus_module.TestFocusClassChild.test_blah`, its parent class is focussed.

### CODE REVIEW

**Comment by delfick** [comment]
ah yeah, I have no problem with that. I'll make a release.

**Comment by delfick** [comment]
do you need python2 support? (if not, I'll probably remove the six requirement and make it python3.4+)

**Comment by delfick** [comment]
actually, I've made and released 0.1.4 with your change, I'll make a new version that's python3 only

**Comment by vbraun** [comment]
I'm still using py2 on a google appengine project but I'm not opposed to py3 only; Celebrate with a 1.0 version 🎉

**Comment by delfick** [comment]
heheh, I very rarely make any of my projects 1.0 :)

But I did release a 0.2.0 which is python3 only, along with updating how I do things like documentation and formatting.

**Pull request merged**
